"""
Converts the exported rules.json and computedStats.json from the UESP build editor
into a MySQL seed SQL file for local development.

Usage: python generate_seed_sql.py
Output: seed.sql
"""

import json
import os

RULES_FILE = os.path.join(os.path.dirname(__file__), "rules.json")
COMPUTED_STATS_FILE = os.path.join(os.path.dirname(__file__), "computedStats.json")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "seed.sql")

RULE_TYPES = {
    "buff", "set", "cp", "passive", "mundus", "active",
    "armorenchant", "weaponenchant", "offhandweaponenchant", "abilitydesc",
}


def q(value):
    """Escape and quote a string value for SQL. Returns NULL for None."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def n(value):
    """Return NULL for None, otherwise a numeric literal."""
    if value is None:
        return "NULL"
    return str(value)


def b(value):
    """Convert bool/truthy to SQL 0 or 1."""
    return "1" if value else "0"


def write_schema(f):
    f.write("""\
-- ============================================================
-- UESP ESO Build Editor -- Local Development Seed
-- Generated by generate_seed_sql.py
-- ============================================================

SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- ------------------------------------------------------------
-- Schema
-- ------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS `esobuilddata`
  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `esobuilddata`;

CREATE TABLE IF NOT EXISTS `versions` (
  `version` TINYTEXT NOT NULL,
  PRIMARY KEY idx_version(`version`(16))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `rules` (
  `id` INTEGER NOT NULL,
  `version` TINYTEXT NOT NULL,
  `ruleType` TINYTEXT NOT NULL,
  `nameId` TINYTEXT,
  `displayName` TINYTEXT,
  `matchRegex` TINYTEXT NOT NULL,
  `displayRegex` TINYTEXT,
  `statRequireId` TINYTEXT,
  `statRequireValue` TINYTEXT,
  `factorStatId` TINYTEXT,
  `isEnabled` TINYINT(1) NOT NULL,
  `isVisible` TINYINT(1) NOT NULL,
  `isToggle` TINYINT(1) NOT NULL,
  `enableOffBar` TINYINT(1) NOT NULL,
  `originalId` TINYTEXT NOT NULL,
  `icon` TINYTEXT NOT NULL,
  `groupName` TINYTEXT NOT NULL,
  `maxTimes` INTEGER,
  `comment` TINYTEXT NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `customData` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX index_version(`version`(10)),
  INDEX index_ruleId(`originalId`(30))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `effects` (
  `id` INTEGER NOT NULL,
  `ruleId` INTEGER NOT NULL,
  `version` TINYTEXT NOT NULL,
  `statId` TINYTEXT NOT NULL,
  `value` TINYTEXT NOT NULL,
  `display` TINYTEXT NOT NULL,
  `category` TINYTEXT NOT NULL,
  `combineAs` TINYTEXT NOT NULL,
  `roundNum` TINYTEXT NOT NULL,
  `factorValue` FLOAT,
  `statDesc` TINYTEXT NOT NULL,
  `buffId` TINYTEXT NOT NULL,
  `regexVar` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX index_ruleId(`ruleId`),
  INDEX index_stat(`statId`(32)),
  INDEX index_version(`version`(10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `computedStats` (
  `id` INTEGER NOT NULL,
  `statId` TINYTEXT NOT NULL,
  `version` TINYTEXT NOT NULL,
  `title` TINYTEXT NOT NULL,
  `roundNum` TINYTEXT NOT NULL,
  `addClass` TINYTEXT NOT NULL,
  `comment` TINYTEXT NOT NULL,
  `minimumValue` FLOAT,
  `maximumValue` FLOAT,
  `deferLevel` TINYINT,
  `display` TINYTEXT NOT NULL,
  `compute` TEXT NOT NULL,
  `idx` TINYINT NOT NULL,
  `category` TINYTEXT NOT NULL,
  `suffix` TINYTEXT NOT NULL,
  `dependsOn` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX index_statId(`statId`(32)),
  INDEX index_version(`version`(10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- esolog-style metadata (footer "last update" in viewCps / viewSkills)
CREATE TABLE IF NOT EXISTS `logInfo` (
  `id` TINYTEXT NOT NULL,
  `value` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`(63))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `logInfo` (`id`, `value`) VALUES
  ('lastCPUpdate', 'local seed'),
  ('lastSkillUpdate', 'local seed')
ON DUPLICATE KEY UPDATE `value` = VALUES(`value`);

-- User build tables (empty schema for personal use)

CREATE TABLE IF NOT EXISTS `characters` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `name` TINYTEXT,
  `buildName` TINYTEXT,
  `wikiUserName` TINYTEXT,
  `class` TINYTEXT,
  `race` TINYTEXT,
  `buildType` TINYTEXT,
  `special` TINYTEXT,
  `alliance` TINYTEXT,
  `level` INTEGER,
  `championPoints` INTEGER,
  `createTime` DATETIME,
  `uploadTimestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `editTimestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `stats` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `name` TINYTEXT,
  `value` MEDIUMTEXT,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `skills` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `name` TINYTEXT,
  `type` TINYTEXT,
  `description` MEDIUMTEXT,
  `abilityId` INTEGER,
  `rank` INTEGER,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `buffs` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `name` TINYTEXT,
  `icon` TINYTEXT,
  `abilityId` INTEGER,
  `description` MEDIUMTEXT,
  `enabled` INTEGER,
  `count` INTEGER,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `championPoints` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `name` TINYTEXT,
  `points` INTEGER,
  `description` MEDIUMTEXT,
  `abilityId` INTEGER,
  `slotIndex` INTEGER,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `actionBars` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `name` TINYTEXT,
  `type` TINYTEXT,
  `description` MEDIUMTEXT,
  `index` INTEGER,
  `icon` TINYTEXT,
  `abilityId` INTEGER,
  `rank` INTEGER,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `inventory` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `account` TINYTEXT,
  `name` TINYTEXT,
  `itemLink` MEDIUMTEXT,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `equipSlots` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `account` TINYTEXT,
  `slotId` TINYTEXT,
  `itemLink` MEDIUMTEXT,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `combatActions` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `rotationName` TINYTEXT,
  `playerActions` MEDIUMTEXT,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `screenshots` (
  `id` INTEGER AUTO_INCREMENT NOT NULL,
  `characterId` INTEGER NOT NULL,
  `filename` TINYTEXT,
  `uploadTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX index_charId(`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cache` (
  `characterId` INTEGER NOT NULL,
  `data` MEDIUMTEXT,
  `updateTime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`characterId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

""")


def write_versions(f, version):
    f.write("-- ------------------------------------------------------------\n")
    f.write("-- Versions\n")
    f.write("-- ------------------------------------------------------------\n\n")
    f.write(f"INSERT INTO `versions` (`version`) VALUES ({q(version)});\n\n")


def write_computed_stats(f, stats_data):
    f.write("-- ------------------------------------------------------------\n")
    f.write("-- computedStats\n")
    f.write("-- ------------------------------------------------------------\n\n")

    rows = []
    for stat_id, stat in stats_data.items():
        if not isinstance(stat, dict):
            continue
        compute_val = stat.get("compute", "[]")
        if isinstance(compute_val, list):
            compute_val = json.dumps(compute_val)
        depends_on = stat.get("dependsOn", "")
        if isinstance(depends_on, list):
            depends_on = json.dumps(depends_on)
        rows.append(
            f"  ({n(stat.get('id'))}, {q(stat.get('statId',''))}, {q(stat.get('version',''))}, "
            f"{q(stat.get('title',''))}, {q(stat.get('roundNum', stat.get('round','')))}, "
            f"{q(stat.get('addClass',''))}, {q(stat.get('comment',''))}, "
            f"{n(stat.get('minimumValue'))}, {n(stat.get('maximumValue'))}, "
            f"{n(stat.get('deferLevel'))}, {q(stat.get('display',''))}, "
            f"{q(compute_val)}, {n(stat.get('idx',0))}, "
            f"{q(stat.get('category',''))}, {q(stat.get('suffix',''))}, "
            f"{q(depends_on)})"
        )

    if rows:
        f.write("INSERT INTO `computedStats` "
                "(`id`,`statId`,`version`,`title`,`roundNum`,`addClass`,`comment`,"
                "`minimumValue`,`maximumValue`,`deferLevel`,`display`,`compute`,"
                "`idx`,`category`,`suffix`,`dependsOn`) VALUES\n")
        f.write(",\n".join(rows))
        f.write(";\n\n")


def write_rules_and_effects(f, rules_data):
    f.write("-- ------------------------------------------------------------\n")
    f.write("-- Rules\n")
    f.write("-- ------------------------------------------------------------\n\n")

    rule_rows = []
    effect_rows = []

    for rule_type, rules_by_id in rules_data.items():
        if rule_type not in RULE_TYPES:
            continue
        if not isinstance(rules_by_id, dict):
            continue
        for rule_id, rule in rules_by_id.items():
            if not isinstance(rule, dict):
                continue
            rule_rows.append(
                f"  ({n(rule.get('id'))}, {q(rule.get('version',''))}, "
                f"{q(rule.get('ruleType',''))}, {q(rule.get('nameId'))}, "
                f"{q(rule.get('displayName'))}, {q(rule.get('matchRegex',''))}, "
                f"{q(rule.get('displayRegex'))}, {q(rule.get('statRequireId',''))}, "
                f"{q(rule.get('statRequireValue',''))}, {q(rule.get('factorStatId',''))}, "
                f"{b(rule.get('isEnabled'))}, {b(rule.get('isVisible'))}, "
                f"{b(rule.get('isToggle'))}, {b(rule.get('enableOffBar'))}, "
                f"{q(rule.get('originalId',''))}, {q(rule.get('icon',''))}, "
                f"{q(rule.get('groupName',''))}, {n(rule.get('maxTimes'))}, "
                f"{q(rule.get('comment',''))}, {q(rule.get('description',''))}, "
                f"{q(rule.get('customData','{}'))})"
            )
            for effect in rule.get("effects", []):
                effect_rows.append(
                    f"  ({n(effect.get('id') or effect.get('effectId'))}, "
                    f"{n(effect.get('ruleId'))}, {q(effect.get('version',''))}, "
                    f"{q(effect.get('statId',''))}, {q(effect.get('value',''))}, "
                    f"{q(effect.get('display',''))}, {q(effect.get('category',''))}, "
                    f"{q(effect.get('combineAs',''))}, "
                    f"{q(effect.get('roundNum', effect.get('round','')))}, "
                    f"{n(effect.get('factorValue'))}, {q(effect.get('statDesc',''))}, "
                    f"{q(effect.get('buffId',''))}, {q(effect.get('regexVar',''))})"
                )

    chunk_size = 500

    for i in range(0, len(rule_rows), chunk_size):
        chunk = rule_rows[i:i + chunk_size]
        f.write("INSERT INTO `rules` "
                "(`id`,`version`,`ruleType`,`nameId`,`displayName`,`matchRegex`,"
                "`displayRegex`,`statRequireId`,`statRequireValue`,`factorStatId`,"
                "`isEnabled`,`isVisible`,`isToggle`,`enableOffBar`,`originalId`,"
                "`icon`,`groupName`,`maxTimes`,`comment`,`description`,`customData`) VALUES\n")
        f.write(",\n".join(chunk))
        f.write(";\n\n")

    f.write("-- ------------------------------------------------------------\n")
    f.write("-- Effects\n")
    f.write("-- ------------------------------------------------------------\n\n")

    for i in range(0, len(effect_rows), chunk_size):
        chunk = effect_rows[i:i + chunk_size]
        f.write("INSERT INTO `effects` "
                "(`id`,`ruleId`,`version`,`statId`,`value`,`display`,`category`,"
                "`combineAs`,`roundNum`,`factorValue`,`statDesc`,`buffId`,`regexVar`) VALUES\n")
        f.write(",\n".join(chunk))
        f.write(";\n\n")


def main():
    print("Reading rules.json ...")
    with open(RULES_FILE, "r", encoding="utf-8") as fh:
        rules_data = json.load(fh)

    # The 'stats' key in rules.json is the raw DB format for computedStats
    stats_data = rules_data.get("stats", {})

    print(f"  Rule types found: {[k for k in rules_data if k in RULE_TYPES]}")
    print(f"  computedStats entries: {len(stats_data)}")

    total_rules = sum(
        len(v) for k, v in rules_data.items()
        if k in RULE_TYPES and isinstance(v, dict)
    )
    total_effects = sum(
        len(rule.get("effects", []))
        for k, v in rules_data.items()
        if k in RULE_TYPES and isinstance(v, dict)
        for rule in v.values()
        if isinstance(rule, dict)
    )
    print(f"  Rules: {total_rules}, Effects: {total_effects}")

    print(f"Writing {OUTPUT_FILE} ...")
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        write_schema(f)
        version = next(
            (r.get("version") for rtype in rules_data.values()
             if isinstance(rtype, dict)
             for r in rtype.values()
             if isinstance(r, dict) and r.get("version")),
            "49"
        )
        write_versions(f, version)
        write_computed_stats(f, stats_data)
        write_rules_and_effects(f, rules_data)
        f.write("SET foreign_key_checks = 1;\n")

    size_mb = os.path.getsize(OUTPUT_FILE) / (1024 * 1024)
    print(f"Done. seed.sql is {size_mb:.1f} MB")


if __name__ == "__main__":
    main()
