#!/usr/bin/env python3
"""
Extract g_EsoCraftedSkills + g_EsoCraftedScripts from a saved Special:EsoBuildEditor HTML
(e.g. curl output) and emit MySQL INSERTs for craftedSkills, craftedScripts, craftedScriptDescriptions.

Usage:
  python scripts/import_crafted_from_wiki_html.py [path/to/eso-build-editor.html]
  python scripts/import_crafted_from_wiki_html.py eso-build-editor.html --out=data/crafted-from-wiki-import.sql

Then apply (pick one):
  mysql -h 127.0.0.1 -u USER -p esobuilddata < data/crafted-from-wiki-import.sql
  php scripts/run-sql-file.php data/crafted-from-wiki-import.sql
  (use the PHP line when `mysql` is not on PATH; uses secrets/esolog.secrets.php)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


def extract_js_object(html: str, var_name: str) -> dict[str, Any]:
    m = re.search(r"var\s+" + re.escape(var_name) + r"\s*=\s*", html)
    if not m:
        raise ValueError(f"Could not find var {var_name} = in HTML")
    start = m.end()
    i = html.find("{", start)
    if i < 0:
        raise ValueError(f"No opening brace for {var_name}")
    depth = 0
    j = i
    while j < len(html):
        c = html[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                j += 1
                break
        j += 1
    else:
        raise ValueError(f"Unclosed object for {var_name}")
    return json.loads(html[i:j])


def sql_str(val: Any) -> str:
    if val is None:
        return "NULL"
    s = str(val)
    s = s.replace("\\", "\\\\").replace("'", "''")
    return "'" + s + "'"


def join_csv(xs: Any) -> str:
    if xs is None:
        return ""
    if isinstance(xs, list):
        return ",".join(str(x) for x in xs)
    return str(xs)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "html_file",
        nargs="?",
        default="eso-build-editor.html",
        help="Saved wiki HTML (default: eso-build-editor.html in cwd)",
    )
    ap.add_argument(
        "--out",
        default="data/crafted-from-wiki-import.sql",
        help="Output SQL path (default: data/crafted-from-wiki-import.sql)",
    )
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[1]
    html_path = Path(args.html_file)
    if not html_path.is_absolute():
        html_path = root / html_path
    if not html_path.is_file():
        print(f"Not found: {html_path}", file=sys.stderr)
        return 1

    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = root / out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)

    text = html_path.read_text(encoding="utf-8", errors="replace")
    skills = extract_js_object(text, "g_EsoCraftedSkills")
    scripts = extract_js_object(text, "g_EsoCraftedScripts")

    lines: list[str] = [
        "-- Generated by scripts/import_crafted_from_wiki_html.py",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS=0;",
        "TRUNCATE TABLE craftedScriptDescriptions;",
        "TRUNCATE TABLE craftedSkills;",
        "TRUNCATE TABLE craftedScripts;",
        "SET FOREIGN_KEY_CHECKS=1;",
        "",
    ]

    # --- craftedScripts
    sid_list = sorted(scripts.keys(), key=lambda k: int(k))
    for sid in sid_list:
        row = scripts[sid]
        rid = int(row["id"])
        slot = int(row.get("slot") or 0)
        lines.append(
            "INSERT INTO craftedScripts (id, name, slot, description, hint, icon) VALUES ("
            f"{rid}, {sql_str(row.get('name'))}, {slot}, {sql_str(row.get('description'))}, "
            f"{sql_str(row.get('hint'))}, {sql_str(row.get('icon'))});"
        )

    lines.append("")

    # --- craftedSkills
    kid_list = sorted(skills.keys(), key=lambda k: int(k))
    for kid in kid_list:
        sk = skills[kid]
        cid = int(sk["id"])
        ability_id = int(sk["abilityId"])
        st = int(sk.get("skillType") or 0)
        desc = sk.get("baseDescription")
        if desc is None or desc == "":
            desc = sk.get("description") or ""
        lines.append(
            "INSERT INTO craftedSkills (id, abilityId, abilityIds, skillType, name, description, hint, icon, slots1, slots2, slots3) VALUES ("
            f"{cid}, {ability_id}, {sql_str(join_csv(sk.get('abilityIds')))}, {st}, "
            f"{sql_str(sk.get('name'))}, {sql_str(desc)}, {sql_str(sk.get('hint'))}, {sql_str(sk.get('icon'))}, "
            f"{sql_str(join_csv(sk.get('slots1')))}, {sql_str(join_csv(sk.get('slots2')))}, {sql_str(join_csv(sk.get('slots3')))});"
        )

    lines.append("")

    # --- craftedScriptDescriptions (from each skill's datas)
    for kid in kid_list:
        sk = skills[kid]
        for _dk, drow in sorted(
            sk.get("datas", {}).items(),
            key=lambda kv: (int(kv[1].get("scriptId", 0)), int(kv[1].get("classId", 0)), int(kv[1].get("id", 0))),
        ):
            if not isinstance(drow, dict):
                continue
            rid = int(drow["id"])
            caid = int(drow["craftedAbilityId"])
            sid = int(drow["scriptId"])
            clid = int(drow.get("classId") or 0)
            abid = int(drow.get("abilityId") or 0)
            lines.append(
                "INSERT INTO craftedScriptDescriptions (id, craftedAbilityId, scriptId, classId, abilityId, name, description) VALUES ("
                f"{rid}, {caid}, {sid}, {clid}, {abid}, {sql_str(drow.get('name'))}, {sql_str(drow.get('description'))});"
            )

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(lines)} lines)")
    print(f"  craftedScripts: {len(sid_list)} rows")
    print(f"  craftedSkills: {len(kid_list)} rows")
    desc_n = sum(len(skills[k].get("datas") or {}) for k in kid_list)
    print(f"  craftedScriptDescriptions: {desc_n} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
